apiVersion: v1
kind: Template
metadata:
  name: image-build-template
  annotations:
    description: "Template to build docker image in OpenShift"
    iconClass: "icon-openjdk"
    tags: "docker-imgage-build"
objects:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: ${imageName}
    spec:
  - kind: Build
    apiVersion: v1
    metadata:
      name: ${imageName}-image-build
    spec:
      source:
        git:
          ref: master
          uri: ${gitURI}
        type: Git
      strategy:
        type: Docker
        dockerStrategy: {}
      output:
        to:
          kind: ImageStreamTag
          name: ${imageName}:latest
parameters:
  - name: imageName
    displayName: Image Name
    description: "Image Name use to create various openshift resource. All lowercase required."
    value: "mule-ee"
    required: true
  - name: gitURI
    displayName: Git URI
    description: "Git URI"
    value: "https://github.com/tanetg/mule-ee-docker"
    required: true